[[SDL2_mixer]]
arch = "i686"
git-tree-sha1 = "67f1bf98e71f9c9c7f3cf8dd99321f2b1c4acc5d"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "4a4ab7c2f541f19b24d96b2255fc85ab9cbd34416d99bf30d5c2b138a1b98465"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.i686-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "i686"
git-tree-sha1 = "4e5bf25205f338939357fdd841f84b350fae5013"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "82cc2c73c151d58c57cfdabaf2929570b257456eac0c120186e2163635952fc6"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.i686-linux-musl.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "9a219d6273cca9b68f1fc298e6065193d543d6f3"
os = "macos"

    [[SDL2_mixer.download]]
    sha256 = "e25bc79bf5147f3bb87ad802fdabc5f3f941c40d2a871034038088fd564c9aef"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.x86_64-apple-darwin14.tar.gz"
[[SDL2_mixer]]
arch = "powerpc64le"
git-tree-sha1 = "9ee27bcc61f232500b786b38dee29a114a232ae5"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "3273eb40f6405a290a88adf17c8360e326c4dc1cb6efe13b78d74e0f06ac018c"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.powerpc64le-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "aarch64"
git-tree-sha1 = "5a5b92f5fd6f7acef2e187cf37aac6dff779a5b5"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "fd336c374a4d7609b343c8475ad1e3f33c72d30b1d1c6e27d239f5e441da3b12"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.aarch64-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "908f15d7d94b7e204fc14aff23d2dfb838e2de09"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "7bfdb53b11d42630cccab00d8b817340a5066201b1bd3fde8c94063e936820cb"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.x86_64-linux-musl.tar.gz"
[[SDL2_mixer]]
arch = "aarch64"
git-tree-sha1 = "1f06a3f74054cd599882e53a45f61618143f68e5"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "96aceb9471dfde6809a35649b654ba48d8b691102a23cfcf5ec97b1fe7b23bc3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.aarch64-linux-musl.tar.gz"
[[SDL2_mixer]]
arch = "armv7l"
git-tree-sha1 = "ac8464ecade06d5ceadcce716d756376e81d86a7"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "c88055114a2d053814997f4d22455d97b0ca03769cbbabc32f6b02ea2c829d47"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.arm-linux-musleabihf.tar.gz"
[[SDL2_mixer]]
arch = "i686"
git-tree-sha1 = "fefbf2b2a7b19c9b5266c56054dbcf47163375fa"
os = "windows"

    [[SDL2_mixer.download]]
    sha256 = "0c45a4cd87694bb6be41b234653a3c747cef56f6ffdb0096912db35906b8bb78"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.i686-w64-mingw32.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "6e1faa176f9b9cf0da52b1570dc11eb6921729af"
os = "freebsd"

    [[SDL2_mixer.download]]
    sha256 = "1945d4568e9d3123a34e55273fddc85b7ec6c12060a3c05c6a64c444e444d1c3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.x86_64-unknown-freebsd11.1.tar.gz"
[[SDL2_mixer]]
arch = "armv7l"
git-tree-sha1 = "4ec972f263946570fcb2ab1ec8aae13689335bcc"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "b2882c007d9640cec50048a6237c2b5fd0c7ddfbf87ac431809417bd23cec2d9"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.arm-linux-gnueabihf.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "bb4ac9edb961d138356a76583151fc34de4d1e73"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "351d8ebd761d23a929a4b9736d8447011b70bf2299748e1e253d650462995abd"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.x86_64-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "828f6660a2fd970e2020255b74df80cb811c3cb3"
os = "windows"

    [[SDL2_mixer.download]]
    sha256 = "1d234f5d91fffc9e55849a14c49382660aba3fb35071bad33d61d565332e1421"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.0.4+1/SDL2_mixer.v2.0.4.x86_64-w64-mingw32.tar.gz"
