[[SDL2_mixer]]
arch = "aarch64"
git-tree-sha1 = "4eee065e78ab6f00bbf410e6e9e9f30ffe269054"
os = "macos"

    [[SDL2_mixer.download]]
    sha256 = "299fdc2df9c16df0c45022fa00c45a24980ae04e0268440838d6c984a4e0be88"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.aarch64-apple-darwin.tar.gz"
[[SDL2_mixer]]
arch = "aarch64"
git-tree-sha1 = "34579ffe49def1a851be5005823a9a3ed881687f"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "ea0a58c5fac64131a536c79c39ee8ed89bc87cafcf26d0d5d10fe7bf2fa04fcf"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.aarch64-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "aarch64"
git-tree-sha1 = "8c7dd741bff5ccd34b05a9e34784177d01d7a89e"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "5bab9c91ebc07d161ad6910d92c9e526661b7748d431f175ae42b05755ebcf00"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.aarch64-linux-musl.tar.gz"
[[SDL2_mixer]]
arch = "aarch64"
git-tree-sha1 = "273c733359498b5c3e79178e29862c855906544f"
os = "freebsd"

    [[SDL2_mixer.download]]
    sha256 = "4e46ad0c5ba3eb28a8a1f9c79a64a66af1a9e50793f99fd6b217bb03d9cca744"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.aarch64-unknown-freebsd.tar.gz"
[[SDL2_mixer]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1aaee60aa73569c12ffe282f5681d3ac89eb115d"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "65b4a738dfd0346fc981654ac955ff923140b0474a78f70fd38fd84aedcfa890"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.armv6l-linux-gnueabihf.tar.gz"
[[SDL2_mixer]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "177a85fce2a77cf021ec4a018711cfa19ef48318"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "f94d5897d2a3124c2d30ef6d56fd1a73f45f14030029cda1302ecaf247fae206"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.armv6l-linux-musleabihf.tar.gz"
[[SDL2_mixer]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40661769aa5c8bac1e4ed05f0ea624a494ec4e60"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "464a1e9026fa6fec21ec502cc113a65a84ba611d99c6efb4d8fdeb481ab895bb"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.armv7l-linux-gnueabihf.tar.gz"
[[SDL2_mixer]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e9be4ce4f67c003167d76eb41c46fc9d224596c"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "414fc5fe69895f4d0570a891e814b5d073e6d73f10b57c58d9731ecaa5ee7edb"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.armv7l-linux-musleabihf.tar.gz"
[[SDL2_mixer]]
arch = "i686"
git-tree-sha1 = "c066039adebf554bfa53b7f57891192dd379d9b9"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "06989d3d6b49c77dd3e2255d684b2bf6d3df374479dc7bd56bdc8ef266676106"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.i686-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "i686"
git-tree-sha1 = "6e610d1301dab2878d4495262492082d4fa2d9fa"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "2d3c0886667e0c752a2de5785d2338f3c4d04a8ac3c2a5589418d8a73c2fe242"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.i686-linux-musl.tar.gz"
[[SDL2_mixer]]
arch = "i686"
git-tree-sha1 = "7f23404c18e80644c87ff6dc09532c6e9f5d66b2"
os = "windows"

    [[SDL2_mixer.download]]
    sha256 = "d2dbe2539d558d64d2ef88f5e64972c0fbf463a003231d012b8de972e33421b3"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.i686-w64-mingw32.tar.gz"
[[SDL2_mixer]]
arch = "powerpc64le"
git-tree-sha1 = "0eb9dec2a028851c3e67ab968460564b6e4dc88c"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "fd24c82789939f0f8a82ab46948277cb7efe943a9e9a731867abcdccca8c20e4"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.powerpc64le-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "riscv64"
git-tree-sha1 = "3e383f44eff00fdc28df5397186600466d35e78c"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "d3e60e811e8015ee15ecf9bfa11e821bad0b0422c6f15247b6ecb43d33367c84"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.riscv64-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "7630d368e5169528eb403441d53080485ad75be5"
os = "macos"

    [[SDL2_mixer.download]]
    sha256 = "149e3dbb74bfffbbe53e2b67aacf1d7fe51c22ce40feea9e79c49dae226a399b"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.x86_64-apple-darwin.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "41b5180f8dcb232b8a0a6d9213452344f45c8601"
libc = "glibc"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "940889d193068d383c6952bf9930dd78f546cb59bb925491b6b868328abffaa5"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.x86_64-linux-gnu.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "3a5c6280aabc46c89a3351aa90e972958ba4a744"
libc = "musl"
os = "linux"

    [[SDL2_mixer.download]]
    sha256 = "2af6b2bbab5e330e5c433587af487a556de09453ba8081410fbb352572e55e46"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.x86_64-linux-musl.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "3b371e34b22a2347b23d595c4fa38c69ab100d6a"
os = "freebsd"

    [[SDL2_mixer.download]]
    sha256 = "7f8040f8df97732eeff37d417035782b4bfe59e10fd4ce0d963d34ec147b5ffa"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.x86_64-unknown-freebsd.tar.gz"
[[SDL2_mixer]]
arch = "x86_64"
git-tree-sha1 = "cb4db86ae06fcc40a6cd15a61a83b49206a57e25"
os = "windows"

    [[SDL2_mixer.download]]
    sha256 = "1032a74c1c51d4d9d4651b82830a3d4aa3030df50591656076c7b6b1c2e6c2bd"
    url = "https://github.com/JuliaBinaryWrappers/SDL2_mixer_jll.jl/releases/download/SDL2_mixer-v2.8.1+0/SDL2_mixer.v2.8.1.x86_64-w64-mingw32.tar.gz"
