# Autogenerated wrapper script for SDL2_mixer_jll for x86_64-apple-darwin
export libsdl2_mixer

using SDL2_jll
JLLWrappers.@generate_wrapper_header("SDL2_mixer")
JLLWrappers.@declare_library_product(libsdl2_mixer, "@rpath/libSDL2_mixer-2.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(SDL2_jll)
    JLLWrappers.@init_library_product(
        libsdl2_mixer,
        "lib/libSDL2_mixer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
